// Mock data for testing the application

export const mockUsers = [
  {
    id: 1,
    name: "Алексей Волков",
    username: "@alexwolf",
    avatar: "/artist-portrait.png",
    bio: "Художник и создатель уникальных артов. Специализируюсь на фурри-арте и комиксах.",
    followers: 1234,
    following: 567,
    itemsSold: 89,
    rating: 4.9,
    verified: true,
    isCreator: true,
    categories: ["Фурри-арт", "Комиксы", "Цифровое искусство"],
    location: "Павильон A, Стенд 42",
    donationEnabled: true,
    donationGoal: 50000,
    donationCurrent: 32500,
  },
  {
    id: 2,
    name: "Мария Светлова",
    username: "@maria_art",
    avatar: "/female-artist.png",
    bio: "Создаю уникальные коллекционные фигурки и мерч по мотивам аниме и игр.",
    followers: 2341,
    following: 234,
    itemsSold: 156,
    rating: 5.0,
    verified: true,
    isCreator: true,
    categories: ["Фигурки", "Аниме", "Мерч"],
    location: "Павильон B, Стенд 15",
    donationEnabled: true,
    donationGoal: 75000,
    donationCurrent: 68000,
  },
]

export const mockAuctions = [
  {
    id: 1,
    title: "Редкая фигурка Sonic the Hedgehog Limited Edition 1/100",
    description:
      "Коллекционная фигурка Соника из лимитированной серии. Только 100 экземпляров в мире. Высота 30см, материал - высококачественный PVC. Включает сертификат подлинности и оригинальную упаковку.",
    images: ["/sonic-figure-collectible.jpg", "/sonic-figure-box.jpg", "/sonic-figure-detail.jpg"],
    currentBid: 2500,
    startingBid: 1000,
    bids: 23,
    timeLeft: "2ч 34м",
    endTime: new Date(Date.now() + 2 * 60 * 60 * 1000 + 34 * 60 * 1000),
    category: "Фигурки",
    seller: mockUsers[0],
    condition: "Новое",
    rarity: "Легендарное",
    views: 1234,
  },
  {
    id: 2,
    title: "Оригинальный арт-принт 'Лунный Волк' с автографом художника",
    description: "Уникальный принт размером 50x70см на премиум бумаге. Подписан художником. Тираж 25 экземпляров.",
    images: ["/wolf-moon-art-print.jpg", "/art-print-signature.jpg"],
    currentBid: 1200,
    startingBid: 500,
    bids: 15,
    timeLeft: "5ч 12м",
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000 + 12 * 60 * 1000),
    category: "Арт",
    seller: mockUsers[1],
    condition: "Новое",
    rarity: "Редкое",
    views: 892,
  },
  {
    id: 3,
    title: "Винтажная футболка Comic-Con 2010 (размер M)",
    description: "Оригинальная футболка с Comic-Con 2010. Отличное состояние, без дефектов.",
    images: ["/comic-con-tshirt-vintage.jpg"],
    currentBid: 450,
    startingBid: 200,
    bids: 8,
    timeLeft: "1д 3ч",
    endTime: new Date(Date.now() + 27 * 60 * 60 * 1000),
    category: "Одежда",
    seller: mockUsers[0],
    condition: "Отличное",
    rarity: "Редкое",
    views: 456,
  },
]

export const mockShopItems = [
  {
    id: 101,
    title: "Значок 'Furry Pride' эмалированный",
    description: "Эмалированный значок высокого качества. Размер 3см.",
    image: "/enamel-pin-furry.jpg",
    price: 350,
    stock: 45,
    category: "Аксессуары",
    seller: mockUsers[0],
    rating: 4.8,
    reviews: 23,
  },
  {
    id: 102,
    title: "Стикерпак 'Anime Vibes' (20 шт)",
    description: "Набор из 20 водостойких стикеров с аниме персонажами.",
    image: "/anime-sticker-pack.png",
    price: 500,
    stock: 120,
    category: "Стикеры",
    seller: mockUsers[1],
    rating: 5.0,
    reviews: 67,
  },
  {
    id: 103,
    title: "Артбук 'Furry Fantasy' 2024",
    description: "Коллекционный артбук с работами 30 художников. 120 страниц.",
    image: "/artbook-fantasy.jpg",
    price: 1500,
    stock: 15,
    category: "Книги",
    seller: mockUsers[0],
    rating: 4.9,
    reviews: 12,
  },
  {
    id: 104,
    title: "Плюшевая игрушка 'Дракон' ручной работы",
    description: "Мягкая игрушка ручной работы, высота 25см.",
    image: "/plush-dragon-toy.jpg",
    price: 2500,
    stock: 8,
    category: "Игрушки",
    seller: mockUsers[1],
    rating: 5.0,
    reviews: 34,
  },
]

export const mockLotteries = [
  {
    id: 1,
    title: "Мега-розыгрыш: Коллекция редких фигурок",
    description: "Выиграй набор из 5 редких коллекционных фигурок общей стоимостью 15000₽!",
    image: "/collectible-figures-set.jpg",
    ticketPrice: 100,
    totalTickets: 1000,
    soldTickets: 743,
    endTime: new Date(Date.now() + 48 * 60 * 60 * 1000),
    prizes: [
      { place: 1, description: "Набор из 5 фигурок", value: 15000 },
      { place: 2, description: "Артбук + стикерпак", value: 2000 },
      { place: 3, description: "Футболка + значки", value: 1000 },
    ],
  },
  {
    id: 2,
    title: "Розыгрыш эксклюзивного арта",
    description: "Получи оригинальный арт от известного художника!",
    image: "/exclusive-artwork.jpg",
    ticketPrice: 200,
    totalTickets: 500,
    soldTickets: 312,
    endTime: new Date(Date.now() + 72 * 60 * 60 * 1000),
    prizes: [
      { place: 1, description: "Оригинальный арт 50x70", value: 10000 },
      { place: 2, description: "Принт с автографом", value: 3000 },
    ],
  },
]

export const mockFeedPosts = [
  {
    id: 1,
    user: mockUsers[0],
    content: "Только что завершил работу над новым артом! Скоро выставлю на аукцион 🎨",
    images: ["/furry-art-new.jpg"],
    likes: 234,
    comments: 45,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    type: "post",
  },
  {
    id: 2,
    user: mockUsers[1],
    content: "Спасибо всем за поддержку! Мы достигли 90% цели по донатам! 💖",
    likes: 567,
    comments: 89,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    type: "announcement",
  },
  {
    id: 3,
    user: mockUsers[0],
    content: "Новая коллекция значков уже в магазине! Успейте купить, пока не разобрали!",
    images: ["/enamel-pins-collection.jpg", "/pins-display.jpg"],
    likes: 123,
    comments: 23,
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    type: "product",
  },
]

export const mockEventMap = {
  areas: [
    {
      id: "toys",
      name: "Игрушки и коллекционные фигурки",
      color: "#3b82f6",
      booths: Array.from({ length: 48 }, (_, i) => ({
        id: `T${i + 1}`,
        number: `${100 + i}`,
        creator: i % 3 === 0 ? mockUsers[i % 2] : null,
      })),
    },
    {
      id: "comics",
      name: "Комиксы, издательства, арт и фотография",
      color: "#8b5cf6",
      booths: Array.from({ length: 36 }, (_, i) => ({
        id: `C${i + 1}`,
        number: `${200 + i}`,
        creator: i % 4 === 0 ? mockUsers[i % 2] : null,
      })),
    },
    {
      id: "pop",
      name: "Поп-культура",
      color: "#06b6d4",
      booths: Array.from({ length: 24 }, (_, i) => ({
        id: `P${i + 1}`,
        number: `${300 + i}`,
        creator: i % 3 === 0 ? mockUsers[i % 2] : null,
      })),
    },
    {
      id: "anime",
      name: "Аниме",
      color: "#ec4899",
      booths: Array.from({ length: 30 }, (_, i) => ({
        id: `A${i + 1}`,
        number: `${400 + i}`,
        creator: i % 5 === 0 ? mockUsers[i % 2] : null,
      })),
    },
    {
      id: "cosplay",
      name: "Косплей",
      color: "#f43f5e",
      booths: Array.from({ length: 18 }, (_, i) => ({
        id: `CS${i + 1}`,
        number: `${500 + i}`,
        creator: i % 4 === 0 ? mockUsers[i % 2] : null,
      })),
    },
  ],
}
